import { Prop, Schema, SchemaFactory } from "@nestjs/mongoose";
import { Document } from "mongoose";

/**
 * Custom order lifecycle -- each status maps to a step in the PRD Flow 2.
 *
 *  pending_review   -> Admin has received the request, not yet quoted.
 *  quoted           -> Admin has set a price + timeline; customer notified.
 *  approved         -> Customer has approved the quote; awaiting payment.
 *  payment_pending  -> Payment initialized; awaiting webhook confirmation.
 *  paid             -> BUSINESS RULE: order enters production ONLY after this.
 *                      Set exclusively by the payment webhook handler.
 *  in_production    -> Production stage tracking begins (see ProductionLog).
 *  completed        -> Final quality check passed, item ready for pickup.
 *  cancelled        -> Cancelled before payment.
 *  refunded         -> Paid order that was later refunded.
 */
export type CustomOrderStatus =
  | "pending_review"
  | "quoted"
  | "approved"
  | "payment_pending"
  | "paid"
  | "in_production"
  | "completed"
  | "cancelled"
  | "refunded";

export type CustomOrderDocument = CustomOrder & Document;

/**
 * Embedded measurement snapshot.
 * When a customer submits a custom order they can either:
 *  (a) reference a saved measurement profile by ID, or
 *  (b) supply inline measurements directly in the request.
 * Either way the service copies the resolved fields here so the order is
 * self-contained -- profile edits after submission do not silently change it.
 */
export class CustomOrderMeasurementSnapshot {
  @Prop({ type: String, default: null })
  profileId: string | null; // null when submitted inline

  @Prop({ required: true, trim: true, lowercase: true })
  garmentType: string;

  @Prop({ type: String, default: null })
  garmentLabel: string | null;

  /** Copied from the resolved profile or inline submission. */
  @Prop({ type: [Object], default: [] })
  fields: { key: string; label: string; value: number }[];
}

@Schema({ timestamps: true, collection: "custom_orders" })
export class CustomOrder {
  // ---- Customer identity ---------------------------------------------------

  /**
   * BUSINESS RULE: a guest can submit a custom order without an account.
   * When the customer later registers/logs in this can be linked via email.
   */
  @Prop({ type: String, default: null, index: true })
  customerId: string | null;

  @Prop({ required: true, trim: true, lowercase: true })
  customerEmail: string;

  @Prop({ required: true, trim: true })
  customerName: string;

  @Prop({ type: String, default: null })
  customerPhone: string | null;

  // ---- Request details -----------------------------------------------------

  /**
   * Human-readable reference number, e.g. "CO-1001".
   * Generated by the service, unique, used in all customer-facing comms.
   */
  @Prop({ required: true, unique: true })
  referenceNumber: string;

  /** Free-text description of the desired piece. */
  @Prop({ required: true, maxlength: 2000 })
  description: string;

  /** Garment category, e.g. "Aso Oke Jacket", "Cargo Pants". */
  @Prop({ required: true, trim: true })
  garmentCategory: string;

  /** Fabric/material preference, e.g. "Aso Oke", "Cotton", "Ankara". */
  @Prop({ type: String, default: null })
  fabricChoice: string | null;

  /** Cloudinary URLs of reference images uploaded by the customer. */
  @Prop({ type: [String], default: [] })
  referenceImages: string[];

  // ---- Measurements snapshot -----------------------------------------------

  @Prop({ type: Object, default: null })
  measurement: CustomOrderMeasurementSnapshot | null;

  // ---- Admin quote ---------------------------------------------------------

  @Prop({ type: Number, default: null, min: 0 })
  quotedPrice: number | null;

  /** ISO-8601 date string, e.g. "2026-09-15". Editable by admin. */
  @Prop({ type: String, default: null })
  estimatedReadyDate: string | null;

  @Prop({ type: String, default: null })
  adminQuoteNote: string | null;

  @Prop({ type: String, default: null })
  quotedBy: string | null; // admin userId

  @Prop({ type: Date, default: null })
  quotedAt: Date | null;

  // ---- Payment -------------------------------------------------------------

  @Prop({ type: String, enum: ["paystack", "flutterwave"], default: null })
  paymentProvider: "paystack" | "flutterwave" | null;

  @Prop({ type: String, default: null, index: true })
  paymentReference: string | null;

  @Prop({ type: String, default: null })
  checkoutUrl: string | null;

  /** Idempotency key -- matches WebhookEvent.eventId. */
  @Prop({ type: String, default: null })
  processedWebhookId: string | null;

  @Prop({ type: Date, default: null })
  paidAt: Date | null;

  // ---- Lifecycle -----------------------------------------------------------

  @Prop({
    type: String,
    enum: [
      "pending_review",
      "quoted",
      "approved",
      "payment_pending",
      "paid",
      "in_production",
      "completed",
      "cancelled",
      "refunded",
    ],
    default: "pending_review",
    index: true,
  })
  status: CustomOrderStatus;

  /**
   * Set once the linked standard Order document is created on payment confirm.
   * Allows admin to view the custom order and regular order together.
   */
  @Prop({ type: String, default: null })
  linkedOrderId: string | null;

  /**
   * Pre-formatted WhatsApp link included in confirmation emails.
   * At launch: click-to-chat only (PRD s.1.8).
   */
  @Prop({ type: String, default: null })
  whatsappLink: string | null;
}

export const CustomOrderSchema = SchemaFactory.createForClass(CustomOrder);

CustomOrderSchema.index({ customerEmail: 1, createdAt: -1 });
CustomOrderSchema.index({ status: 1, createdAt: -1 });
CustomOrderSchema.index({ customerId: 1, createdAt: -1 });
